"""add total_visits column

Revision ID: 105ae4d5e123
Revises: 60a45e008ae2
Create Date: 2025-12-18 18:14:25.442375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105ae4d5e123'
down_revision: Union[str, Sequence[str], None] = '60a45e008ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_urls', sa.Column('total_visits', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_urls', 'total_visits')
    # ### end Alembic commands ###
