"""init

Revision ID: 60a45e008ae2
Revises: 
Create Date: 2025-12-18 15:29:55.259964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60a45e008ae2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_urls_original_url'), 'short_urls', ['original_url'], unique=False)
    op.create_index(op.f('ix_short_urls_short_code'), 'short_urls', ['short_code'], unique=True)
    op.create_table('url_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url_id', sa.Integer(), nullable=False),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['short_url_id'], ['short_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_visits')
    op.drop_index(op.f('ix_short_urls_short_code'), table_name='short_urls')
    op.drop_index(op.f('ix_short_urls_original_url'), table_name='short_urls')
    op.drop_table('short_urls')
    # ### end Alembic commands ###
