"""add expires_at to shorturl

Revision ID: 0a7b25dc54ae
Revises: 105ae4d5e123
Create Date: 2026-09-06 22:45:24.796758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7b25dc54ae'
down_revision: Union[str, Sequence[str], None] = '105ae4d5e123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_urls', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_urls', 'expires_at')
    # ### end Alembic commands ###
